### ISSUE TITLE
Editable version of Figure 1

### ISSUE THREAD

**Issue by khawar-islam** [JinXins/Adversarial-AutoMixup#1]
Dear @JinXins 

Thanks for your contribution and fantastic work. I am also working on data augmentation domain and I have a request if you can consider it. Would it be possible for you to share the code/editable file of top-1 accuracy graph in figure 1 and mixup-based images? It would be extremely helpful for me, please consider it.

Best regards,
Khawar

**Comment by JinXins** [comment]
**Dear Islam**
&ensp;&ensp; Thanks for your compliments! You can find the code for the top-1 accuracy graph in Figure 1 in **OpenMixup**.
```
openmixup/tools/analysis_tools/analyze_logs.py
You can start it with the command:
python tools/analysis_tools/analyze_logs.py plot_curve exp_1.logs.json exp_2.log.json --key acc_top1
```
And the mixup-based images I will update to my repo, the code about creating mixup-based images you can write in `mixup_classification.py` if you want to create images based dynamic mixup methods like *PuzzleMix, AutoMix, or AdAutoMix*, or other static mixup methods you can run the `vis_sample.py`.

Thanks for your issue!
Kind  regards,
Xin Jin

**Comment by khawar-islam** [comment]
Dear Jin @JinXins thank you very much for your swift reply and help.

**Comment by JinXins** [comment]
Dear Islam,
if you like my work, please give me a **star** and **cite** it. Thanks.

**Comment by khawar-islam** [comment]
Sure

**Comment by khawar-islam** [comment]
Hello @JinXins Would it be possible for you to share the .json file for accuracy of  SOTA to reconstruct figure 1 accuracy curve?

**Comment by JinXins** [comment]
I'm sorry Islam. I'm now enjoying my vacation and Chinese New Year. I can't share the .json file these days, because these files in my other computer. you can wait maybe half a month. Sorry!!

**Comment by khawar-islam** [comment]
@JinXins no problem sure enjoyment is mandatory happy new year (Guo Nian) too. When you get back, please share with me

**Comment by JinXins** [comment]
Of course. Thank you for the good wishes. haha.

**Comment by khawar-islam** [comment]
@JinXins when your vacation end, please send me .json file for accuracy

**Comment by JinXins** [comment]
Dear islam,
    Sorry to say that I have finished my vacation today. Just got to the lab a few minutes ago and I have uploaded the accuracy file in Figure 1. You can find in **experiments->CIFAR100->Mixups_r18_200epoch_json**.

**Comment by khawar-islam** [comment]
Dear @JinXins thank you so much.

**Comment by khawar-islam** [comment]
Hello @JinXins based on you code and json file, I have reproduced accuracy graph but it does not look same like yours. Are there anything missing? I want same graph like in yours paper. Also, there is no key top1 in json file

`python3 openmixup/openmixup/tools/analysis_tools/analyze_logs.py plot_curve experiments/CIFAR100/Mixups_r18_200epoch_json/CutMix.json experiments/CIFAR100/Mixups_r18_200epoch_json/GridMix.json experiments/CIFAR100/Mixups_r18_200epoch_json/PuzzleMix.json --key acc_mix`


![Figure_1](https://github.com/JinXins/Adversarial-AutoMixup/assets/11488932/0a24560b-f22f-4ead-b429-414040d875b9)

**Comment by JinXins** [comment]
Dear islam,
 You can use my analyze_logs.py.And set *key* to **acc_top1**
