### ISSUE TITLE
I want adautomix to operate in an independent environment.

### ISSUE THREAD

**Issue by KUKUDAS95** [JinXins/Adversarial-AutoMixup#2]
Is it possible to operate adautomix by downloading only github from jinxins?(do not use westlake-ai openmixup)

I want adautomix to operate in an independent environment.

**Comment by JinXins** [comment]
Hi, @KUKUDAS95 . For me, it's taking some time to get this done. Maybe **I'll follow up by adding other files to adautomix**, but of course **I'll need to apply with the organisers of OpenMixup**. Thanks for your suggestions!
