### ISSUE TITLE
Figure 4 Individual figure and code

### ISSUE THREAD

**Issue by khawar-islam** [JinXins/Adversarial-AutoMixup#4]
Hello @JinXins 

I hope this message finds you well. I am reaching out for a bit of assistance regarding the calibration **code** referenced in Figure 4 of your work. If you could kindly provide it, it would be incredibly helpful for me.

I have already trained the models and now need to evaluate their confidence levels. Your help would save me a significant amount of time.

Thank you in advance for your support!

Best regards,
Khawar

**Comment by JinXins** [comment]
Hi @khawar-islam . The calibration metric code you can find in ``tools/analysis_tools/calibration_fgsm.py``. no.164 line and the ``ece_socre`` core codes you could find in ``openmixup/datasets/classification.py`` no.120 line
